class CreateCountries
  def self.run
    [
      {:iso=>"af", :name=>"Afeganistão"},
      {:iso=>"ax", :name=>"Ilhas Åland"},
      {:iso=>"al", :name=>"Albânia"},
      {:iso=>"dz", :name=>"Argélia"},
      {:iso=>"as", :name=>"Samoa Americana"},
      {:iso=>"ad", :name=>"Andorra"},
      {:iso=>"ao", :name=>"Angola"},
      {:iso=>"ai", :name=>"Anguila"},
      {:iso=>"aq", :name=>"Antártida"},
      {:iso=>"ag", :name=>"Antígua e Barbuda"},
      {:iso=>"ar", :name=>"Argentina"},
      {:iso=>"am", :name=>"Armênia"},
      {:iso=>"aw", :name=>"Aruba"},
      {:iso=>"au", :name=>"Austrália"},
      {:iso=>"at", :name=>"Áustria"},
      {:iso=>"az", :name=>"Azerbaijão"},
      {:iso=>"bs", :name=>"Bahamas"},
      {:iso=>"bh", :name=>"Barém"},
      {:iso=>"bd", :name=>"Bangladexe"},
      {:iso=>"bb", :name=>"Barbados"},
      {:iso=>"by", :name=>"Bielorrússia"},
      {:iso=>"be", :name=>"Bélgica"},
      {:iso=>"bz", :name=>"Belize"},
      {:iso=>"bj", :name=>"Benim"},
      {:iso=>"bm", :name=>"Bermudas"},
      {:iso=>"bt", :name=>"Butão"},
      {:iso=>"bo", :name=>"Bolívia"},
      {:iso=>"bq", :name=>"Países Baixos Caribenhos"},
      {:iso=>"ba", :name=>"Bósnia e Herzegovina"},
      {:iso=>"bw", :name=>"Botsuana"},
      {:iso=>"bv", :name=>"Ilha Bouvet"},
      {:iso=>"br", :name=>"Brasil"},
      {:iso=>"io", :name=>"Território Britânico do Oceano Índico"},
      {:iso=>"bn", :name=>"Brunei"},
      {:iso=>"bg", :name=>"Bulgária"},
      {:iso=>"bf", :name=>"Burquina Fasso"},
      {:iso=>"bi", :name=>"Burundi"},
      {:iso=>"kh", :name=>"Camboja"},
      {:iso=>"cm", :name=>"Camarões"},
      {:iso=>"ca", :name=>"Canadá"},
      {:iso=>"cv", :name=>"Cabo Verde"},
      {:iso=>"ky", :name=>"Ilhas Caimã"},
      {:iso=>"cf", :name=>"República Centro-Africana"},
      {:iso=>"td", :name=>"Chade"},
      {:iso=>"cl", :name=>"Chile"},
      {:iso=>"cn", :name=>"China"},
      {:iso=>"cx", :name=>"Ilha do Natal"},
      {:iso=>"cc", :name=>"Ilhas Cocos (Keeling)"},
      {:iso=>"co", :name=>"Colômbia"},
      {:iso=>"km", :name=>"Comores"},
      {:iso=>"cg", :name=>"República do Congo"},
      {:iso=>"cd", :name=>"República Democrática do Congo"},
      {:iso=>"ck", :name=>"Ilhas Cook"},
      {:iso=>"cr", :name=>"Costa Rica"},
      {:iso=>"ci", :name=>"Costa do Marfim"},
      {:iso=>"hr", :name=>"Croácia"},
      {:iso=>"cu", :name=>"Cuba"},
      {:iso=>"cw", :name=>"Curaçau"},
      {:iso=>"cy", :name=>"Chipre"},
      {:iso=>"cz", :name=>"Chéquia"},
      {:iso=>"dk", :name=>"Dinamarca"},
      {:iso=>"dj", :name=>"Djibuti"},
      {:iso=>"dm", :name=>"Dominica"},
      {:iso=>"do", :name=>"República Dominicana"},
      {:iso=>"ec", :name=>"Equador"},
      {:iso=>"eg", :name=>"Egito"},
      {:iso=>"sv", :name=>"El Salvador"},
      {:iso=>"gq", :name=>"Guiné Equatorial"},
      {:iso=>"er", :name=>"Eritreia"},
      {:iso=>"ee", :name=>"Estónia"},
      {:iso=>"et", :name=>"Etiópia"},
      {:iso=>"fk", :name=>"Ilhas Malvinas"},
      {:iso=>"fo", :name=>"Ilhas Feroé"},
      {:iso=>"fj", :name=>"Fiji"},
      {:iso=>"fi", :name=>"Finlândia"},
      {:iso=>"fr", :name=>"França"},
      {:iso=>"gf", :name=>"Guiana Francesa"},
      {:iso=>"pf", :name=>"Polinésia Francesa"},
      {:iso=>"tf", :name=>"Terras Austrais e Antárticas Francesas"},
      {:iso=>"ga", :name=>"Gabão"},
      {:iso=>"gm", :name=>"Gâmbia"},
      {:iso=>"ge", :name=>"Geórgia"},
      {:iso=>"de", :name=>"Alemanha"},
      {:iso=>"gh", :name=>"Gana"},
      {:iso=>"gi", :name=>"Gibraltar"},
      {:iso=>"gr", :name=>"Grécia"},
      {:iso=>"gl", :name=>"Gronelândia"},
      {:iso=>"gd", :name=>"Granada"},
      {:iso=>"gp", :name=>"Guadalupe"},
      {:iso=>"gu", :name=>"Guam"},
      {:iso=>"gt", :name=>"Guatemala"},
      {:iso=>"gg", :name=>"Guernsey"},
      {:iso=>"gn", :name=>"Guiné"},
      {:iso=>"gw", :name=>"Guiné-Bissau"},
      {:iso=>"gy", :name=>"Guiana"},
      {:iso=>"ht", :name=>"Haiti"},
      {:iso=>"hm", :name=>"Ilha Heard e Ilhas McDonald"},
      {:iso=>"va", :name=>"Vaticano"},
      {:iso=>"hn", :name=>"Honduras"},
      {:iso=>"hk", :name=>"Hong Kong"},
      {:iso=>"hu", :name=>"Hungria"},
      {:iso=>"is", :name=>"Islândia"},
      {:iso=>"in", :name=>"Índia"},
      {:iso=>"id", :name=>"Indonésia"},
      {:iso=>"ir", :name=>"Irã"},
      {:iso=>"iq", :name=>"Iraque"},
      {:iso=>"ie", :name=>"Irlanda"},
      {:iso=>"im", :name=>"Ilha de Man"},
      {:iso=>"il", :name=>"Israel"},
      {:iso=>"it", :name=>"Itália"},
      {:iso=>"jm", :name=>"Jamaica"},
      {:iso=>"jp", :name=>"Japão"},
      {:iso=>"je", :name=>"Jersey"},
      {:iso=>"jo", :name=>"Jordânia"},
      {:iso=>"kz", :name=>"Cazaquistão"},
      {:iso=>"ke", :name=>"Quênia"},
      {:iso=>"ki", :name=>"Quiribáti"},
      {:iso=>"kp", :name=>"Coreia do Norte"},
      {:iso=>"kr", :name=>"Coreia do Sul"},
      {:iso=>"kw", :name=>"Kuwait"},
      {:iso=>"kg", :name=>"Quirguistão"},
      {:iso=>"la", :name=>"Laos"},
      {:iso=>"lv", :name=>"Letônia"},
      {:iso=>"lb", :name=>"Líbano"},
      {:iso=>"ls", :name=>"Lesoto"},
      {:iso=>"lr", :name=>"Libéria"},
      {:iso=>"ly", :name=>"Líbia"},
      {:iso=>"li", :name=>"Listenstaine"},
      {:iso=>"lt", :name=>"Lituânia"},
      {:iso=>"lu", :name=>"Luxemburgo"},
      {:iso=>"mo", :name=>"Macau"},
      {:iso=>"mk", :name=>"Macedônia do Norte"},
      {:iso=>"mg", :name=>"Madagáscar"},
      {:iso=>"mw", :name=>"Maláui"},
      {:iso=>"my", :name=>"Malásia"},
      {:iso=>"mv", :name=>"Maldivas"},
      {:iso=>"ml", :name=>"Mali"},
      {:iso=>"mt", :name=>"Malta"},
      {:iso=>"mh", :name=>"Ilhas Marshall"},
      {:iso=>"mq", :name=>"Martinica"},
      {:iso=>"mr", :name=>"Mauritânia"},
      {:iso=>"mu", :name=>"Ilhas Maurícias"},
      {:iso=>"yt", :name=>"Maiote"},
      {:iso=>"mx", :name=>"México"},
      {:iso=>"fm", :name=>"Estados Federados da Micronésia"},
      {:iso=>"ma", :name=>"Marrocos"},
      {:iso=>"md", :name=>"Moldávia"},
      {:iso=>"mc", :name=>"Mónaco"},
      {:iso=>"mn", :name=>"Mongólia"},
      {:iso=>"me", :name=>"Montenegro"},
      {:iso=>"ms", :name=>"Monserrate"},
      {:iso=>"mz", :name=>"Moçambique"},
      {:iso=>"mm", :name=>"Mianmar"},
      {:iso=>"na", :name=>"Namíbia"},
      {:iso=>"nr", :name=>"Nauru"},
      {:iso=>"np", :name=>"Nepal"},
      {:iso=>"nl", :name=>"Países Baixos"},
      {:iso=>"nc", :name=>"Nova Caledônia"},
      {:iso=>"nz", :name=>"Nova Zelândia"},
      {:iso=>"ni", :name=>"Nicarágua"},
      {:iso=>"ne", :name=>"Níger"},
      {:iso=>"ng", :name=>"Nigéria"},
      {:iso=>"nu", :name=>"Niue"},
      {:iso=>"nf", :name=>"Ilha Norfolk"},
      {:iso=>"mp", :name=>"Marianas Setentrionais"},
      {:iso=>"no", :name=>"Noruega"},
      {:iso=>"om", :name=>"Omã"},
      {:iso=>"pk", :name=>"Paquistão"},
      {:iso=>"pw", :name=>"Palau"},
      {:iso=>"ps", :name=>"Palestina"},
      {:iso=>"pa", :name=>"Panamá"},
      {:iso=>"pg", :name=>"Papua-Nova Guiné"},
      {:iso=>"py", :name=>"Paraguai"},
      {:iso=>"pe", :name=>"Peru"},
      {:iso=>"ph", :name=>"Filipinas"},
      {:iso=>"pn", :name=>"Pitcairn"},
      {:iso=>"pl", :name=>"Polónia"},
      {:iso=>"pt", :name=>"Portugal"},
      {:iso=>"pr", :name=>"Porto Rico"},
      {:iso=>"qa", :name=>"Catar"},
      {:iso=>"re", :name=>"Reunião"},
      {:iso=>"ro", :name=>"Roménia"},
      {:iso=>"ru", :name=>"Rússia"},
      {:iso=>"rw", :name=>"Ruanda"},
      {:iso=>"bl", :name=>"São Bartolomeu"},
      {:iso=>"sh", :name=>"Santa Helena, Ascensão e Tristão da Cunha"},
      {:iso=>"kn", :name=>"São Cristóvão e Neves"},
      {:iso=>"lc", :name=>"Santa Lúcia"},
      {:iso=>"mf", :name=>"São Martinho"},
      {:iso=>"pm", :name=>"São Pedro e Miquelão"},
      {:iso=>"vc", :name=>"São Vicente e Granadinas"},
      {:iso=>"ws", :name=>"Samoa"},
      {:iso=>"sm", :name=>"San Marino"},
      {:iso=>"st", :name=>"São Tomé e Príncipe"},
      {:iso=>"sa", :name=>"Arábia Saudita"},
      {:iso=>"sn", :name=>"Senegal"},
      {:iso=>"rs", :name=>"Sérvia"},
      {:iso=>"sc", :name=>"Seicheles"},
      {:iso=>"sl", :name=>"Serra Leoa"},
      {:iso=>"sg", :name=>"Singapura"},
      {:iso=>"sx", :name=>"São Martinho"},
      {:iso=>"sk", :name=>"Eslováquia"},
      {:iso=>"si", :name=>"Eslovênia"},
      {:iso=>"sb", :name=>"Ilhas Salomão"},
      {:iso=>"so", :name=>"Somália"},
      {:iso=>"za", :name=>"África do Sul"},
      {:iso=>"gs", :name=>"Ilhas Geórgia do Sul e Sandwich do Sul"},
      {:iso=>"ss", :name=>"Sudão do Sul"},
      {:iso=>"es", :name=>"Espanha"},
      {:iso=>"lk", :name=>"Seri Lanca"},
      {:iso=>"sd", :name=>"Sudão"},
      {:iso=>"sr", :name=>"Suriname"},
      {:iso=>"sj", :name=>"Esvalbarde e Jan Mayen"},
      {:iso=>"sz", :name=>"Essuatíni"},
      {:iso=>"se", :name=>"Suécia"},
      {:iso=>"ch", :name=>"Suíça"},
      {:iso=>"sy", :name=>"Síria"},
      {:iso=>"tw", :name=>"Taiwan"},
      {:iso=>"tj", :name=>"Tajiquistão"},
      {:iso=>"tz", :name=>"Tanzânia"},
      {:iso=>"th", :name=>"Tailândia"},
      {:iso=>"tl", :name=>"Timor-Leste"},
      {:iso=>"tg", :name=>"Togo"},
      {:iso=>"tk", :name=>"Toquelau"},
      {:iso=>"to", :name=>"Tonga"},
      {:iso=>"tt", :name=>"Trinidad e Tobago"},
      {:iso=>"tn", :name=>"Tunísia"},
      {:iso=>"tr", :name=>"Turquia"},
      {:iso=>"tm", :name=>"Turcomenistão"},
      {:iso=>"tc", :name=>"Turcas e Caicos"},
      {:iso=>"tv", :name=>"Tuvalu"},
      {:iso=>"ug", :name=>"Uganda"},
      {:iso=>"ua", :name=>"Ucrânia"},
      {:iso=>"ae", :name=>"Emirados Árabes Unidos"},
      {:iso=>"gb", :name=>"Reino Unido"},
      {:iso=>"us", :name=>"Estados Unidos"},
      {:iso=>"um", :name=>"Ilhas Menores Distantes dos Estados Unidos"},
      {:iso=>"uy", :name=>"Uruguai"},
      {:iso=>"uz", :name=>"Uzbequistão"},
      {:iso=>"vu", :name=>"Vanuatu"},
      {:iso=>"ve", :name=>"Venezuela"},
      {:iso=>"vn", :name=>"Vietname"},
      {:iso=>"vg", :name=>"Ilhas Virgens Britânicas"},
      {:iso=>"vi", :name=>"Ilhas Virgens Americanas"},
      {:iso=>"wf", :name=>"Wallis e Futuna"},
      {:iso=>"eh", :name=>"Saara Ocidental"},
      {:iso=>"ye", :name=>"Iêmen"},
      {:iso=>"zm", :name=>"Zâmbia"},
      {:iso=>"zw", :name=>"Zimbábue"}
    ].each do |country|
      Country.find_or_create_by(country)
    end
  end

  def self.rollback 
    Country.destroy_all
  end
end
